FROM golang:1.12-alpine

RUN apk add --no-cache git

# Set the Current Working Directory inside the container
WORKDIR /app

# We want to populate the module cache based on the go.{mod,sum} files.
COPY go.mod .
COPY go.sum .

RUN go mod download
RUN go get github.com/githubnemo/CompileDaemon

COPY . /app

# Build the Go app
#RUN go build -o ./out/main ./cmd/main.go


# Run the binary program produced by `go install`
#CMD ["./out/main"]
ENTRYPOINT CompileDaemon --build="go build ./cmd/main.go" --command=./main